---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    permissions: contents:write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18
    - run: npm ci
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        node-version: 18
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Build"
        files: |
          *.vsix
